### ISSUE TITLE
Preserve string quote style

### ISSUE THREAD

**Issue by skovhus** [facebook/jscodeshift#143]
I would except jscodeshift and recast to preserve the original string quote style after a transformation. It does that for existing quotes, but when creating or changing literals, they always end up as double quoted in the output. At least that is the case for `ImportDeclaration`.

Any plans on preserving the original string quote style? It is rather easy to guess it based on the `rawValue` from the parser.

Let me know if I can help out.

### Example

```javascript 
export default function transformer(file, api) {
  const j = api.jscodeshift;
  const ast = j(file.source);
  ast.find(j.ImportDeclaration, {
    source: {
      type: 'Literal',
      value: 'foo',
    }
  })
  .forEach(p => {
    p.node.source.value = 'foo2';
  });    
  return ast.toSource();
};
```

tranforms 
```javascript
import foo from 'foo';
foo('', {x: 'baz'});
```

to 
```javascript
import foo from "foo2";
foo('', {x: 'baz'});
```

Try it out here http://astexplorer.net/#/LGuntllww9/3

**Comment by hzoo** [comment]
Right as far as I know, recast preserves the source/formatting of code that isn't modified - however for code that does change it has a hardcoded format (since it doesn't know a user's preferences). In this particular case it would be possible - I proposed using an eslintrc or something to do in https://github.com/benjamn/recast/issues/226

**Comment by skovhus** [comment]
@hzoo thanks. 

Yes, eslintrc or similar configuration is one option... But would also be neat to just detect it on surrounding code.

**Comment by fkling** [comment]
See https://github.com/facebook/jscodeshift#passing-options-to-recast for how to set which quotes to use.

Not really a jscodeshift issue since jscodeshift doesn't do the printing. I guess we *could* set the right option automatically, but this seems to be something that recast should simply be doing itself. However, if someone wants to create a PR for this I am happy to review it.
