### ISSUE TITLE
compile before publish for lower environment

### ISSUE THREAD

**Issue by jaredleechn** [facebook/jscodeshift#164]
Since using jscodeshift in `main.js` of an electron app , when I package the app, it error some unexpected keyword like [class] (https://github.com/facebook/jscodeshift/blob/master/src/Collection.js#L32) for the bundler never compile files under node_modules
```
ERROR in ./main.js from UglifyJs
SyntaxError: Unexpected token: name (Collection) [../my-component/~/.0.3.29@jscodeshift/dist/Collection.js:32,0]
```

So how about making a compile before publish, or adding a compiled version into dist, because it's a complex job to fork and follow-up this repository.

I can make a pr doing something like follow:

```diff
-    "build:cp": "cp -R src/ dist/",
+    "build:compile": "babel src --out-dir dist/compiled --ignore __tests__",
+    "build": "npm run build:cp && npm run build:compile",

```

**Comment by fkling** [comment]
We used to do this, but it's unnecessary because we only use features that are supported by all the environments jscodeshift supports.

I'm not really familiar with electron, but I assume it will also use at least node v4. 

The problem you encounter is that UglifyJS doesn't support ES6. So you should either use a different minifier or configure your packager to convert jscodeshift like we did in astexplorer: https://github.com/fkling/astexplorer/blob/master/webpack.config.js#L90

**Comment by jaredleechn** [comment]
All right, get it! 😼

**Comment by abhishiv** [comment]
Hey @fkling, but this means that the api can't be used with webpack in the browser because it throws an error on this. Or am I missing something obvious?

**Comment by fkling** [comment]
@abhishiv, you can configure webpack to apply babel to jscodeshift. As I mentioned in my previous comment, [that's what we did in astexplorer](https://github.com/fkling/astexplorer/blob/13c2d5db93d59bf51a78335d8c2c84f4a1ae1a3f/webpack.config.js#L90).
