### ISSUE TITLE
Why transformer add brackets to spread conditions

### ISSUE THREAD

**Issue by HichamELBSI** [facebook/jscodeshift#176]
Hi guys,

All in the title :D see the example below

input : 
```javascript
...
const menu = [
      ...test && test2,
      ...test && test2,
 ];
```

output : 
```javascript
...
const menu = [
      ...(test && test2),
      ...(test && test2),
 ];
```

**Comment by fkling** [comment]
Printing is done by https://github.com/benjamn/recast . I assume it has a generic rule for wrapping certain expression in parenthesis. You can raise an issue, or even better, a pull request, there.

It seems that happens even without any changes to the AST, so that's certainly a concern to raise since untouched lines should not be changed.
