### ISSUE TITLE
Is there a way to specify end-of-line characters?

### ISSUE THREAD

**Issue by tw0517tw** [facebook/jscodeshift#195]
Hi, I'm using Windows when my team has others using Mac.
Our .editorconfig specifies that we use `\n` as EOL character, I've also set my .gitconfig `autocrlf=input`.
So when we write test fixtures for codemods, there are `\n`s in the files.
But when running tests, the output will have `\r\n`s, causing tests fail on my machine.

I'm wondering if there is a way to specify EOL characters when running jscodeshift?

**Comment by keyanzhang** [comment]
Yeah, you can pass the `lineTerminator` option to Recast: https://github.com/facebook/jscodeshift#passing-options-to-recast

https://github.com/benjamn/recast/blob/master/lib/options.js#L20-L21

**Comment by tw0517tw** [comment]
thanks! problem solved.

**Comment by jakezatecky** [comment]
To add to that, you can supply the following option to the CLI command to fix this broken default behavior:

``` bash
--printOptions='{"lineTerminator":"\n"}'
```

Side rant: It's really nice that you have to search through a myriad of issues and dependencies to determine that some developers arbitrarily decided that it was a good idea to use the OS line endings rather than honor the contents of the original file or default to the sane LF character. It's further great that there is no mention of this in the README of this repo or the `react-codemod` repo to warn users of this arbitrary design decision that will likely break tests as @tw0517tw mentions.

**Comment by fkling** [comment]
@jakezatecky, while I understand your frustration and I agree with you about the matter itself, ranting is not helpful. All the code is open source. You can help make this better by either submitting PRs for updating the READMEs, or make a PR to recast to enable line break detection (although in this case there already seems to be one https://github.com/benjamn/recast/pull/311).

**Comment by jakezatecky** [comment]
@fkling I agree a rant is not helpful, and I apologize for directing some of the steam to this issue.

Because this is in a dependency, and not the library itself, I thought it unlikely that any PR suggesting a notice on line-feeds would be accepted. In particular, since the official recommendation to account for breaking changes in React v15.5 is to run a set of FB-provided scripts, I was hesitant to make the PR in `react-codemode`, because the dependency (recast) of its dependency (jscodeshift) was the underlying issue, and it seems silly to document this two levels up.

I'll look into submitting a PR to that repo rectifying this over the weekend. Although I think this repo is possibly a more appropriate place to notate this, I think more value can be obtained from its depedent.

**Comment by ksummerlin** [comment]
Do you have an example for passing it on the command line? I cannot get the --printOptions to work. I tried this:

```
jscodeshift --printOptions='{"lineTerminator":"\n"}' \
-t transforms/React-PropTypes-to-prop-types.js \
/my-react-app
```

which transforms the files, but I still get the wrong line terminators.

**Comment by jakezatecky** [comment]
@ksummerlin Your command looks correct. Unfortunately, this works on some of the scripts, but not all. I have a PR open that consistently consumes the `printOptions` on all scripts, but it has not been reviewed yet by the collaborators:

https://github.com/reactjs/react-codemod/pull/145
