### ISSUE TITLE
How to transform comments in a line.

### ISSUE THREAD

**Issue by dashokkumar93** [facebook/jscodeshift#236]
I have js code like this.
```
var opensource="Github";
var Qa="Stackoverflow";
```

I want to identify whether a line contains a string literal and if there is and add a comment such as

```
var opensource="Github"; //Not for translation
var Qa="Stackoverflow"; //Not for translation
```

I know it can done using finding literals and check whether that literal node line contains a string and if there is no comment add one. The problem is how to access the comment in a line dynamically using jscodeshift?.

**Comment by benjamn** [comment]
Once you've found the node by traversing the AST, just add comments to it as an array:
```js
const comment = builders.Line(" Not for translation");
comment.trailing = true;
varDecl.comments = node.comments || [];
varDecl.comments.push(comment);
```
However, trailing `//` line comments don't always end up where you want them (sometimes they get printed on a line above the node), so I would recommend a slightly different strategy:
```js
// Put a /* block comment */ immediately after the string literal:
const comment = builders.Block(" Not for translation ");
comment.trailing = true;
stringLiteral.comments = stringLiteral.comments || [];
stringLiteral.comments.push(comment);
```
If all goes well, this should produce
```js
var opensource="Github" /* Not for translation */;
var Qa="Stackoverflow" /* Not for translation */;
```
I don't know the details of your translation tools, so I'm not sure if this will work as well as trailing `//` comments, but it would be great if it did, since `/* block comments */` tend to be much more resilient to surviving AST transformations.

In any case, that's the gist of how you add comments to the AST.
