### ISSUE TITLE
`remove` method remove console will remove comment before it

### ISSUE THREAD

**Issue by mfoonirlee** [facebook/jscodeshift#271]
I have write a transformer like below:
```javascript
export default function (file, api){
    const j = api.jscodeshift;
    const ast = j(file.source); 
    return ast.find(j.Statement).filter(path => {
        return j(path).find(j.CallExpression, {
            callee: {
                type: 'MemberExpression',
                object: {
                    type: 'Identifier', 
                    name: 'console'
                },
            },
        }).size();
    }).forEach(path => {
       j(path).remove(); // will remove comment
    }).toSource();
}
```
when I run with case below:( by using `j(path).remove()`)
```javascript
import a from 'geometry';

console.log('This is a console');

const area = a.getCircleArea(radius);

var thisIsAVarible = 'abc';
// if(thisIsAVarible){
//     console.log('hello world');
// }

console.log(thisIsAVarible);
```
It would remove comments in code, I got the result like:
```javascript
import a from 'geometry';


const area = a.getCircleArea(radius);

var thisIsAVarible = 'abc';


```
I have no idea what`s the matter with my transformer, Is there any idea?

**Comment by fkling** [comment]
Handling comments can be tricky. Comments are not their own nodes in an AST, there are associated with another node. You can see [here](https://astexplorer.net/#/gist/8c8dcfc02889a42b1baf6092ad5bc582/0bddde477a58994fa6436160b71f7599de09c9a7) that the comments are associated with the `console.log` statement. This is why the comments are removed when if you remove the call.

One possible solution (haven't checked) would be to check whether `path.node.comments` is set and "copy" the comment to the previous node if they they are, e.g. `previousNode.comments = node.comments;`.

However, sometimes you probably do want to remove the comment, e.g. in this case:

```
// Log debug info
console.log(data);
```

That's why handling comments is tricky, there usually isn't "the right way" to deal with them.
