### ISSUE TITLE
Newlines stripped from processed files

### ISSUE THREAD

**Issue by pieterv** [facebook/jscodeshift#28]
new lines seem to be removed even if i dont change a file, for now i am having to do:
```
return root.toSource({quote: 'single', trailingComma: true}) + '\n';
```

Maybe this is an issue with `recast`?

**Comment by pieterv** [comment]
Hmm maybe this fixes it, https://github.com/benjamn/recast/issues/199

**Comment by fkling** [comment]
Mmh, have to look at the recast thing, but also have a look at #27.

**Comment by cpojer** [comment]
@fkling this is exactly what I mentioned yesterday. *Everyone* gets tripped up by this. Let's just merge #27 with the auto-detection? That should cover this really nicely without a "breaking" change.

**Comment by fkling** [comment]
@cpojer: I know, I was just wondering what recast did about this since it was mentioned there as well.

**Comment by fkling** [comment]
So, the issue seems to be with using Babel as parser. If esprima is used, trailing and leading whitespace is preserved. I'd suggest we first look into if we can fix this in recast before making changes to jscodeshift.

**Comment by fkling** [comment]
OK, I know what the issue is. `recast.parse(...)` returns a `File` AST node which contains the location information about the leading and trailing white spaces, but since we are throwing that object away and only use `program` in https://github.com/facebook/jscodeshift/blob/master/src/core.js#L74, we are loosing that information.

Maybe everything will just work if we use the `File` object instead.

**Comment by pieterv** [comment]
Awesome! Thanks @fkling

**Comment by fkling** [comment]
Release in v0.3.3 btw.

**Comment by nebirhos** [comment]
It looks like this is an issue again in v0.4.0.

**Comment by ibrahima** [comment]
Aha, ran into this issue as well. I can confirm that downgrading to v0.3.32 fixes the issue.
