### ISSUE TITLE
can we run jscodeshift in .graphql files?

### ISSUE THREAD

**Issue by sibelius** [facebook/jscodeshift#333]
how can I change parser to handle .graphql files?

**Comment by jedwards1211** [comment]
I don't think it's possible, since whatever the parser returns has to be compatible with `recast`, which is specific to JS/TS.  However, the CLI does have an `extensions` option, and as the readme mentions your transform function can use any tool to modify the source code, so it's definitely possible to run a transform on .graphql files.  I just don't think it's possible to use JSCodeshift's Collection API on GraphQL.

**Comment by sibelius** [comment]
tks
