### ISSUE TITLE
Collection.reverse

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/jscodeshift#68]
I wonder if we could add a `reverse` helper on to the collection class. Currently I'm doing this:

``` js
const reverseCollection = collection => j(collection.paths().reverse());
```

I need to reverse the collection to perform operations on nested call expressions, so I can start at the deep end and traverse up, copying across old nodes as I please.

**Comment by fkling** [comment]
Not sure if this issue is still relevant to you, but anyways: I don't think we guarantee that the order of elements in the collection corresponds to the order in which the appear in the source. We could probably guarantee this easily by sorting on each node's `loc` or `range` property, but I wonder if this is really necessary.

At the moment, adding such a method would give a false impression of guarantee IMO. Feel free to reopen if you feel strongly about this.
