### ISSUE TITLE
Console output from transforms is silently swallowed

### ISSUE THREAD

**Issue by spudly** [facebook/jscodeshift#81]
I'm trying to run transformations but having a really hard time because all my files get skipped and I have no indication of why.

Each of the transformation files use console.log() to tell the user why files were skipped, but for whatever reason, the console.log() statements never make it into stdout.

**Comment by fkling** [comment]
Mmh, not sure. According to the docs, `child_process.fork()` should forward everything to the parent's stdout by default.

However, even if it worked, I'm not sure it would be useful, since the workers run concurrently and any output produced by the child processes might be intermingled with the output of the parent process.

Have you considered using the [`stats` function](https://github.com/facebook/jscodeshift#api) instead? It Only works in in dry runs, but lets you output valuably information.

**Comment by DrewML** [comment]
Not sure if something changed in the codebase that enabled this, but this works with the current versions of `jscodeshift`. Verified with the following transform:

```javascript
export default function transformer(file, api) {
    console.log('heyyyyyyy');
    return null;
};
```

**Comment by fkling** [comment]
Yep, works fine for me too.

**Comment by danielo515** [comment]
This does not shows everything though:

```js
module.exports = function (file, api) {
  const j = api.jscodeshift;
  const { statement } = j.template;
  console.log("Starting"); // this is shown
  return j(file.source)
    .find(j.FunctionExpression)
    .replaceWith((p) => {
      console.log("What the", p);
      const root = j(p.value);
      const variablesToReplace = {};
      return p;
    });
};
```

**Comment by danielo515** [comment]
sorry, my bad, I was using FunctionExpression to look for ArrowFunctionExpressions. It works.
